create table FUNCIONARIOS_FUNC(
	FUNC_IDFUNCIONARIO	INTEGER			IDENTITY(1,1),
	FUNC_NOME			NVARCHAR(50)	NOT NULL,
	FUNC_MATRICULA		NVARCHAR(12)	NOT NULL,
	FUNC_LOGIN			NVARCHAR(25)	NOT NULL,
	FUNC_SENHA			NVARCHAR(100)	NOT NULL,
	PRIMARY KEY(FUNC_IDFUNCIONARIO)
)
go

CREATE TABLE FORNECEDOR_FORN(
	FORN_IDFORNECEDOR	INTEGER			IDENTITY(1,1),
	FORN_NOME			NVARCHAR(50)	NOT NULL,
	PRIMARY KEY(FORN_IDFORNECEDOR)
)
GO

CREATE TABLE PRODUTOS_PROD(
	PROD_IDPRODUTO		INTEGER			IDENTITY(1,1),
	PROD_NOME			NVARCHAR(50)	NOT NULL,
	PROD_PRECO			MONEY			NOT NULL DEFAULT 0,
	PROD_QUANTIDADE		INTEGER			NOT NULL DEFAULT 0,
	PROD_DESCRICAO		NVARCHAR(250)	NULL,
	PROD_IDFORNECEDOR	INTEGER			NOT NULL,
	PRIMARY KEY(PROD_IDPRODUTO),
	FOREIGN KEY(PROD_IDFORNECEDOR) REFERENCES FORNECEDOR_FORN(FORN_IDFORNECEDOR)
)
